<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="6" total="10" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="297" started-at="2019-04-05T12:23:13Z" finished-at="2019-04-05T12:23:13Z">
    <groups>
      <group name="aaa">
        <method signature="B.m5()[pri:0, instance:mavenproj.B@5056dfcb]" name="m5" class="mavenproj.B"/>
        <method signature="MavenTest.m4()[pri:0, instance:mavenproj.MavenTest@b97c004]" name="m4" class="mavenproj.MavenTest"/>
      </group> <!-- aaa -->
    </groups>
    <test name="Default test" duration-ms="297" started-at="2019-04-05T12:23:13Z" finished-at="2019-04-05T12:23:13Z">
      <class name="mavenproj.B">
        <test-method status="FAIL" signature="m10()[pri:0, instance:mavenproj.B@5056dfcb]" test-instance-name="" name="m10" duration-ms="0" started-at="2019-04-05T17:53:13Z" finished-at="2019-04-05T17:53:13Z">
          <exception class="java.lang.IllegalAccessException">
            <message>
              <![CDATA[Class org.testng.internal.MethodInvocationHelper can not access a member of class mavenproj.B with modifiers "public"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalAccessException: Class org.testng.internal.MethodInvocationHelper can not access a member of class mavenproj.B with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:101)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:295)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:287)
	at java.lang.reflect.Method.invoke(Method.java:476)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalAccessException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m10 -->
        <test-method status="FAIL" signature="m5()[pri:0, instance:mavenproj.B@5056dfcb]" test-instance-name="" name="m5" duration-ms="0" started-at="2019-04-05T17:53:13Z" finished-at="2019-04-05T17:53:13Z">
          <exception class="java.lang.IllegalAccessException">
            <message>
              <![CDATA[Class org.testng.internal.MethodInvocationHelper can not access a member of class mavenproj.B with modifiers "public"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalAccessException: Class org.testng.internal.MethodInvocationHelper can not access a member of class mavenproj.B with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:101)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:295)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:287)
	at java.lang.reflect.Method.invoke(Method.java:476)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalAccessException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m5 -->
        <test-method status="FAIL" signature="m7()[pri:0, instance:mavenproj.B@5056dfcb]" test-instance-name="" name="m7" duration-ms="0" started-at="2019-04-05T17:53:13Z" finished-at="2019-04-05T17:53:13Z">
          <exception class="java.lang.IllegalAccessException">
            <message>
              <![CDATA[Class org.testng.internal.MethodInvocationHelper can not access a member of class mavenproj.B with modifiers "public"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalAccessException: Class org.testng.internal.MethodInvocationHelper can not access a member of class mavenproj.B with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:101)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:295)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:287)
	at java.lang.reflect.Method.invoke(Method.java:476)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalAccessException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m7 -->
        <test-method status="FAIL" signature="m6()[pri:0, instance:mavenproj.B@5056dfcb]" test-instance-name="" name="m6" duration-ms="0" started-at="2019-04-05T17:53:13Z" finished-at="2019-04-05T17:53:13Z">
          <exception class="java.lang.IllegalAccessException">
            <message>
              <![CDATA[Class org.testng.internal.MethodInvocationHelper can not access a member of class mavenproj.B with modifiers "public"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalAccessException: Class org.testng.internal.MethodInvocationHelper can not access a member of class mavenproj.B with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:101)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:295)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:287)
	at java.lang.reflect.Method.invoke(Method.java:476)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalAccessException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m6 -->
        <test-method status="FAIL" signature="m8()[pri:0, instance:mavenproj.B@5056dfcb]" test-instance-name="" name="m8" duration-ms="0" started-at="2019-04-05T17:53:13Z" finished-at="2019-04-05T17:53:13Z">
          <exception class="java.lang.IllegalAccessException">
            <message>
              <![CDATA[Class org.testng.internal.MethodInvocationHelper can not access a member of class mavenproj.B with modifiers "public"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalAccessException: Class org.testng.internal.MethodInvocationHelper can not access a member of class mavenproj.B with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:101)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:295)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:287)
	at java.lang.reflect.Method.invoke(Method.java:476)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalAccessException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m8 -->
        <test-method status="FAIL" signature="m9()[pri:0, instance:mavenproj.B@5056dfcb]" test-instance-name="" name="m9" duration-ms="16" started-at="2019-04-05T17:53:13Z" finished-at="2019-04-05T17:53:13Z">
          <exception class="java.lang.IllegalAccessException">
            <message>
              <![CDATA[Class org.testng.internal.MethodInvocationHelper can not access a member of class mavenproj.B with modifiers "public"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalAccessException: Class org.testng.internal.MethodInvocationHelper can not access a member of class mavenproj.B with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:101)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:295)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:287)
	at java.lang.reflect.Method.invoke(Method.java:476)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalAccessException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m9 -->
      </class> <!-- mavenproj.B -->
      <class name="mavenproj.MavenTest">
        <test-method status="PASS" signature="m3()[pri:0, instance:mavenproj.MavenTest@b97c004]" name="m3" duration-ms="31" started-at="2019-04-05T17:53:13Z" finished-at="2019-04-05T17:53:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m3 -->
        <test-method status="PASS" signature="m4()[pri:0, instance:mavenproj.MavenTest@b97c004]" name="m4" duration-ms="15" started-at="2019-04-05T17:53:13Z" finished-at="2019-04-05T17:53:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m4 -->
        <test-method status="SKIP" signature="m2()[pri:0, instance:mavenproj.MavenTest@b97c004]" name="m2" duration-ms="0" depends-on-groups="aaa" started-at="2019-04-05T17:53:13Z" finished-at="2019-04-05T17:53:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MavenTest.m2()[pri:0, instance:mavenproj.MavenTest@b97c004] depends on not successfully finished methods in group "aaa"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MavenTest.m2()[pri:0, instance:mavenproj.MavenTest@b97c004] depends on not successfully finished methods in group "aaa"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m2 -->
        <test-method status="SKIP" signature="m1()[pri:0, instance:mavenproj.MavenTest@b97c004]" name="m1" duration-ms="0" started-at="2019-04-05T17:53:13Z" depends-on-methods="mavenproj.MavenTest.m2" finished-at="2019-04-05T17:53:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MavenTest.m1()[pri:0, instance:mavenproj.MavenTest@b97c004] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MavenTest.m1()[pri:0, instance:mavenproj.MavenTest@b97c004] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m1 -->
      </class> <!-- mavenproj.MavenTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
